name: ReleaseTasks
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildnumber:
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.buildnumber.outputs.build_number }}
    steps:
    - name: Generate a build number
      id: buildnumber
      uses: einaregilsson/build-number@v3
      with:
        token: ${{ secrets.github_token }}
    
  build:
    needs: buildnumber
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.3
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
    #  - name: Install GitVersion
    #    uses: gittools/actions/gitversion/setup@v0.9.7
    #    with: 
    #      versionSpec: '5.x'
          
    #  - name: Determine Version
    #    id: gitversion
    #    uses: gittools/actions/gitversion/execute@v0.9.7
    #    with:
    #      additionalArguments: '/updateAssemblyInfo'
        
      - name: Restore NuGet Packages
        run: nuget restore TestLibrary/TestLibrary.sln
        
      - name: Build Solution
        run: msbuild TestLibrary/TestLibrary.sln /property:Configuration=Debug
        
      - name: Take CPZ
        run: |
          mkdir built
          $newFilePath = ".\built\TestLibrary" + ${env:BUILD_NUMBER} + ".dll"
          mv .\TestLibrary\bin\Debug\TestLibrary.dll $newFilePath
                  
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftp
          local-dir: built/
          server-dir: /Broadway/software/debug/
