name: Testing
on:
  push:
    branches: [ main ]

jobs:  
  calver:
    name: CalVer
    runs-on: ubuntu-latest
    steps:
      - name: Calver Release
        uses: StephaneBour/actions-calver@v1.3
        id: calver
        with:
          release_branch: main
          date_format: "%Y.%m.%d.%H%M%S"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - shell: bash
        env:
          CALVER: ${{steps.calver.outputs.release}}
        run: |
          x=$CALVER
          echo "Buid number is"
          echo $x
          echo $x >> calver.txt
          
      - name: Read and assign
        id: output_test
        run: |
          input_file="calver.txt"
          while read line
          do
          file_text=$line
          done < "$input_file"
          echo ::set-output name=new_value::$file_text
      
      - name: get var
        run: echo ${{steps.output_test.outputs.new_value}}
      
      - name: Upload CalVer
        uses: actions/upload-artifact@v2
        with:
          name: calver
          path: calver.txt
